#!/usr/bin/env python3
"""DRE-3432, Observation 1 — the OFFLINE replay of agent-bureau PR #2370.

Drives bureau-pipeline's real `reconcile.recover_crashed_reviews()` (at the
commit the fleet runs, extracted under ./bp) over the captured history of
dreadnought-foundry/agent-bureau#2370 on 2026-09-08, through the same seam
`tests/test_reviewer_environment_sweep.py`'s `_World` uses: `subprocess.run`
is replaced for the length of each sweep, and `linear_ops.comment_bodies` /
`linear_ops.cmd_comment` are replaced with an in-memory card. NOTHING here can
reach GitHub, Linear or AWS: any `gh` call the fake does not recognise raises,
and the network is refused outright while a sweep runs.

What is REAL and what is SYNTHESIZED is printed in the output and listed in
observation-1.md. In one line: the comment thread, every timestamp, the three
crash logs, the run/attempt records and the sweep clock are captured; the
medic's evidence note is GENERATED by the real writer from the real log; the
check-run and run-list answers are the captured records read AS OF each
sweep's moment (GitHub serves today's state; the records carry the times).

Run (from this directory):
    GH_TOKEN=x ./venv/bin/python replay_2370.py            # both variants + the control
    GH_TOKEN=x ./venv/bin/python replay_2370.py --json replay-result.json
"""
from __future__ import annotations

import argparse
import contextlib
import io
import json
import os
import socket
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

HERE = Path(__file__).resolve().parent
BP = HERE / "bp"
FX = HERE / "fixture"

# Dummy credentials BEFORE anything is imported: an env GH_TOKEN overrides any
# keychain login, so even an unpatched `gh` could not authenticate.
os.environ["GH_TOKEN"] = "x"
os.environ.pop("GH_DISPATCH_TOKEN", None)
os.environ["LINEAR_API_KEY"] = "test-key"
os.environ["REPO"] = "dreadnought-foundry/agent-bureau"
os.environ["REPO_SLUG"] = "agent-bureau"
sys.path.insert(0, str(BP / "scripts"))

import medic_classify  # noqa: E402
import reconcile  # noqa: E402
import reviewer_environment as renv  # noqa: E402

REPO = "dreadnought-foundry/agent-bureau"
PR_NUMBER = 2370
CARD = "DRE-3388"
PT = timezone(timedelta(hours=-7), "PT")  # PDT on 2026-09-08


def _load(name):
    return json.loads((FX / name).read_text(encoding="utf-8"))


def _t(iso: str) -> datetime:
    return datetime.fromisoformat(iso.replace("Z", "+00:00"))


def _pt(iso: str) -> str:
    return _t(iso).astimezone(PT).strftime("%Y-%m-%d %H:%M:%S PT")


# --------------------------------------------------------------------------- #
# the captured history                                                         #
# --------------------------------------------------------------------------- #
PR = _load("pr-graphql-comments.json")          # gh pr view --json … comments
CRASHED_HEAD = "81bcc242cc03da6c6f90b864252dca81be9783cc"
REAL_COMMENTS = PR["comments"]                  # GraphQL shape, as the sweep reads
LINEAR = _load("linear-DRE-3388-comments-window.json")["comments"]
RECONCILE_RUNS = _load("reconcile-runs-window.json")["workflow_runs"]

#: The three identical crashes: (label, run id, attempt, job id, event).
CRASHES = [
    ("crash 1", 34286800645, 1, 102264152565),
    ("crash 2", 34287604200, 1, 102266703991),
    ("crash 3", 34287604200, 2, 102272082240),
]

#: Every workflow_dispatch run of qa-review.yml in the window, by attempt —
#: what `gh run list --workflow qa-review.yml --event workflow_dispatch` read.
DISPATCH_RUNS = {
    34286416550: [1, 2, 3],
    34286419990: [1, 2, 3],
    34287604200: [1, 2],
    34292201434: [1],
}

#: The real sweep clock: reconcile.yml's SCHEDULE runs (the full sweep). The
#: repository_dispatch reconcile runs in the window are the one-card
#: promote hook and do not run the crashed-review recovery.
SWEEP_CLOCK = sorted(
    (r["created_at"], r["id"]) for r in RECONCILE_RUNS
    if r["event"] == "schedule"
    and "2026-09-08T22:46:00Z" <= r["created_at"] <= "2026-09-08T23:47:00Z"
)

#: Real comments that are the OLD sweep's own output. The replay's sweep writes
#: its own, so these are left out of what it is fed and compared afterwards.
REAL_REDISPATCH_RECEIPT = next(
    c for c in REAL_COMMENTS
    if reconcile.CRASHED_REVIEW_DISPATCH_TAG in c["body"]
    and c["author"]["login"].removesuffix("[bot]") == reconcile.WORKER_BOT_LOGIN
)
REAL_MEDIC_LITERAL_ID = "9caf1f28-7c87-4c44-bb57-bc41ae34e495"
REAL_REVIEWER_DOWN_ID = "b08ef24e-91fd-4c10-8fbf-4bdb71fd14a8"


def crash_facts():
    """Each crash, named off the captured records, with the REAL detector and
    the REAL medic classifier run over its REAL log."""
    out = []
    for label, run_id, attempt, job_id in CRASHES:
        jobs = _load(f"qa-review-run-{run_id}-attempt{attempt}-jobs.json")["jobs"]
        run = _load(f"qa-review-run-{run_id}-attempt{attempt}.json")
        job = next(j for j in jobs if j["id"] == job_id)
        failed = next(s for s in job["steps"] if s["conclusion"] == "failure")
        log = (FX / f"job-{job_id}.log").read_text(encoding="utf-8", errors="replace")
        signature = renv.detect(log)
        out.append({
            "label": label, "run_id": run_id, "attempt": attempt,
            "job_id": job_id, "event": run["event"],
            "triggered_by": (run.get("triggering_actor") or {}).get("login"),
            "run_started": _pt(run["run_started_at"]),
            "failed_step": failed["name"],
            "failed_at": _pt(failed["started_at"]),
            "job_completed": _pt(job["completed_at"]),
            "signature": signature.slug if signature else None,
            "medic_class": medic_classify.classify(run["name"], log),
            "run_url": run["html_url"],
        })
    return out


def evidence_note() -> tuple[str, str]:
    """The medic's evidence note for crash 1, GENERATED: the real detector over
    the real log names the signature, and the real writer composes the note
    with the real head sha and the real run URL — the three things medic.yml's
    `backoff` job passes to `reviewer_environment.py note`. Placed at the
    moment the medic REALLY left its (old, rate-limit) note on the card."""
    log = (FX / "job-102264152565.log").read_text(encoding="utf-8", errors="replace")
    signature = renv.detect(log)
    assert signature is not None, "crash 1's real log carries no environment signature"
    run = _load("qa-review-run-34286800645-attempt1.json")
    assert run["head_sha"] == CRASHED_HEAD
    at = next(c["createdAt"] for c in LINEAR if c["id"] == REAL_MEDIC_LITERAL_ID)
    return at, renv.evidence_note(signature, run["head_sha"], run["html_url"])


# --------------------------------------------------------------------------- #
# what GitHub would have answered AT a given moment (reconstructed)            #
# --------------------------------------------------------------------------- #
def review_checks_at(now: str) -> str:
    """`gh api …/commits/<head>/check-runs --jq '[… endswith("review") …]'` as
    of `now` — the sweep's own jq filter, applied in Python to the CAPTURED
    `?filter=all` listing, which still holds every attempt's check run: attempt
    1's crashed `call / review` (102264152565), attempt 2's later success
    (102288350419) and the head-bound `QA critic review` (102264839064).

    ONE thing is time-travel rather than capture: the default listing the sweep
    reads is `filter=latest` — one row per name, the newest — so for each name
    the newest check run that had STARTED by `now` is the row.

    `conclusion` is NOT time-travelled. It is read straight off the captured
    listing for every record, including the head-bound `QA critic review`
    (102264839064), which is a single record patched in place: created at crash
    1 (captured `started_at`), carrying the 17:26 PT verdict's text by capture
    time. There is no substitution keyed on that id anywhere in this file, and
    what it read at 15:46 PT is not recoverable from a capture taken on
    2026-09-20. (Docstring corrected 2026-09-22: this text previously claimed
    the conclusion was "taken as `failure`". It never was — the code below has
    always read the captured field. The description was fixed rather than the
    code, because this file is a frozen artifact; see
    `docs/reviewer-environment-hold-proof.md`.)"""
    by_name: dict[str, dict] = {}
    for run in _load("check-runs-81bcc242-filter-all.json")["check_runs"]:
        if not run["name"].endswith("review") or now < run["started_at"]:
            continue
        held = by_name.get(run["name"])
        if held is None or run["started_at"] > held["started_at"]:
            by_name[run["name"]] = run
    rows = []
    for run in sorted(by_name.values(), key=lambda r: r["started_at"]):
        done = now >= run["completed_at"]
        rows.append(["completed" if done else "in_progress",
                     (run["conclusion"] or "") if done else "", run["name"]])
    return json.dumps(rows)


def dispatch_runs_at(now: str) -> list[dict]:
    """`gh run list --workflow qa-review.yml --event workflow_dispatch --json
    status` as of `now`, RECONSTRUCTED from every captured attempt record:
    in_progress while `now` falls inside an attempt, completed otherwise."""
    out = []
    for run_id, attempts in DISPATCH_RUNS.items():
        recs = [_load(f"dispatch-run-{run_id}-attempt{a}.json")
                if run_id != 34287604200
                else _load(f"qa-review-run-{run_id}-attempt{a}.json")
                for a in attempts]
        if now < recs[0]["run_started_at"]:
            continue  # not dispatched yet
        live = any(r["run_started_at"] <= now < r["updated_at"] for r in recs)
        out.append({"status": "in_progress" if live else "completed",
                    "_run_id": run_id})
    return out


# --------------------------------------------------------------------------- #
# the world the sweep runs in                                                  #
# --------------------------------------------------------------------------- #
class Replay:
    def __init__(self, use_real_receipt: bool, with_note: bool = True):
        #: False = the CONTROL: the card as it really was (the medic's old
        #: rate-limit literal, no evidence note).
        self.with_note = with_note
        #: variant B feeds the REAL 15:47 PT re-dispatch receipt; variant A
        #: leaves it out because its own 15:46 sweep writes one.
        self.use_real_receipt = use_real_receipt
        self.posted_pr: list[dict] = []     # what the replayed sweeps posted
        self.posted_card: list[tuple[str, str]] = []  # (createdAt, body)
        self.note_at, self.note = evidence_note()
        self.now = ""
        self.calls: list[list[str]] = []

    # --- state as of `now` --------------------------------------------------
    def pr_comments(self) -> list[dict]:
        real = [
            {"author": c["author"], "body": c["body"], "createdAt": c["createdAt"]}
            for c in REAL_COMMENTS
            if c["createdAt"] < self.now
            and (self.use_real_receipt or c is not REAL_REDISPATCH_RECEIPT)
        ]
        return sorted(real + self.posted_pr, key=lambda c: c["createdAt"])

    def listing(self) -> list[dict]:
        return [{
            "number": PR_NUMBER,
            "headRefName": PR["headRefName"],
            "headRefOid": CRASHED_HEAD,      # the head at the time (captured commits)
            "baseRefName": PR["baseRefName"],
            "mergeStateStatus": "CLEAN",     # SYNTHESIZED — not recoverable today
            "isDraft": False,
            "comments": self.pr_comments(),
        }]

    def card_bodies(self, identifier: str) -> list[str]:
        assert identifier == CARD, identifier
        rows = []
        for c in LINEAR:
            if c["createdAt"] >= self.now or c["id"] == REAL_REVIEWER_DOWN_ID:
                continue
            body = (self.note if self.with_note and c["id"] == REAL_MEDIC_LITERAL_ID
                    else c["body"])
            rows.append((c["createdAt"], body))
        rows += [r for r in self.posted_card]
        return [b for _, b in sorted(rows)]

    # --- the fake `gh` -------------------------------------------------------
    def _stamp(self) -> str:
        at = _t(self.now) + timedelta(seconds=45 + len(self.posted_pr))
        return at.strftime("%Y-%m-%dT%H:%M:%SZ")

    def run(self, argv, **_kw):
        assert argv[0] == "gh", f"unexpected process: {argv}"
        self.calls.append(list(argv))
        ok = lambda out="": SimpleNamespace(returncode=0, stdout=out, stderr="")  # noqa: E731
        if argv[1:3] == ["pr", "list"]:
            return ok(json.dumps(self.listing()))
        if argv[1] == "api" and f"/commits/{CRASHED_HEAD}/check-runs" in argv[2]:
            return ok(review_checks_at(self.now))
        if argv[1] == "api" and ("/compare/" in argv[2] or "/commits?" in argv[2]):
            return ok("")  # unreadable, as the test harness answers: no content carry
        if argv[1:3] == ["run", "list"]:
            return ok(json.dumps(dispatch_runs_at(self.now)))
        if argv[1:3] == ["workflow", "run"]:
            return ok()  # RECORDED in self.calls; nothing is dispatched
        if argv[1:3] == ["pr", "comment"]:
            assert argv[3] == str(PR_NUMBER)
            self.posted_pr.append({
                "author": {"login": "agent-bureau-bot"},
                "body": argv[argv.index("--body") + 1],
                "createdAt": self._stamp(),
            })
            return ok()
        raise AssertionError(f"the replay has no answer for: {argv}")

    def card_comment(self, identifier, body):
        assert identifier == CARD, identifier
        self.posted_card.append((self._stamp(), body))

    # --- one sweep -----------------------------------------------------------
    def sweep(self, now: str) -> dict:
        self.now = now
        reconcile.reset_sweep_cards()
        reconcile._write_failures.clear()
        reconcile._read_failures.clear()
        renv.POST_FAILURES.clear()
        before = (len(self.calls), len(self.posted_pr), len(self.posted_card))
        checks, runs = review_checks_at(now), dispatch_runs_at(now)

        def no_network(*_a, **_k):
            raise AssertionError("the replay is offline — a socket was opened")

        log = io.StringIO()
        with patch.object(reconcile.subprocess, "run", side_effect=self.run), \
                patch.object(renv.subprocess, "run", side_effect=self.run), \
                patch.object(socket, "create_connection", side_effect=no_network), \
                patch.object(socket.socket, "connect", side_effect=no_network), \
                patch.object(reconcile.linear_ops, "comment_bodies",
                             side_effect=self.card_bodies), \
                patch.object(reconcile.linear_ops, "cmd_comment",
                             side_effect=self.card_comment), \
                contextlib.redirect_stdout(log), contextlib.redirect_stderr(log):
            reconcile.recover_crashed_reviews()
        calls = self.calls[before[0]:]
        return {
            "simulated_time_utc": now,
            "simulated_time_pt": _pt(now),
            "review_checks_at_head": json.loads(checks),
            "dispatch_runs": runs,
            "pr_thread_size_fed": len(self.pr_comments()) - (len(self.posted_pr) - before[1]),
            "dispatched": [c for c in calls if c[1:3] == ["workflow", "run"]],
            "pr_receipts_posted": [c["body"] for c in self.posted_pr[before[1]:]],
            "card_comments_posted": [b for _, b in self.posted_card[before[2]:]],
            "write_failures": list(reconcile._write_failures),
            "read_failures": list(reconcile._read_failures),
            "sweep_log": log.getvalue().strip().splitlines(),
        }


def _kind(body: str) -> str:
    if renv.HOLD_TAG in body:
        return "HOLD (runner-environment-hold)"
    if reconcile.CRASHED_REVIEW_DISPATCH_TAG in body:
        return "re-dispatch receipt (crashed-review-redispatch)"
    if reconcile.REVIEWER_DOWN_TAG in body:
        return "reviewer-down report"
    return "other"


def drive(use_real_receipt: bool) -> list[dict]:
    world = Replay(use_real_receipt)
    clock = SWEEP_CLOCK[1:] if use_real_receipt else SWEEP_CLOCK
    rows = []
    for at, reconcile_run in clock:
        row = world.sweep(at)
        row["real_reconcile_run_id"] = reconcile_run
        rows.append(row)
    return rows


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", help="also write the full result here")
    args = ap.parse_args()

    stable = _load("../stable-ref.json")["object"]["sha"]
    print(f"bureau-pipeline driven: stable = {stable}")
    print(f"PR #{PR_NUMBER}: crashed head {CRASHED_HEAD}; merged head "
          f"{PR['headRefOid']} (state {PR['state']})\n")

    crashes = crash_facts()
    print("THE THREE CRASHES (captured records; detector + medic classifier run on the real logs)")
    for c in crashes:
        print(f"  {c['label']}: run {c['run_id']} attempt {c['attempt']} "
              f"({c['event']}, by {c['triggered_by']}), job {c['job_id']} — "
              f"'{c['failed_step']}' failed {c['failed_at']}; "
              f"signature={c['signature']} medic class={c['medic_class']}")
    note_at, note = evidence_note()
    print(f"\nTHE MEDIC'S EVIDENCE NOTE (GENERATED by reviewer_environment.evidence_note; "
          f"placed on {CARD} at {_pt(note_at)}, where the medic really left its old note):")
    print("  | " + note.replace("\n", "\n  | "))

    result = {"bureau_pipeline_stable_sha": stable, "crashes": crashes,
              "evidence_note": {"placed_at_utc": note_at, "body": note},
              "variants": {}}
    verdicts = {}
    for name, real in (("A: five sweeps from 15:46 PT, the replay writes its own re-dispatch receipt", False),
                       ("B: four sweeps from 16:04 PT, over the REAL thread incl. the real re-dispatch receipt", True)):
        rows = drive(real)
        result["variants"][name] = rows
        print(f"\n=== VARIANT {name} ===")
        for i, row in enumerate(rows, 1):
            receipts = row["pr_receipts_posted"]
            print(f"\n  sweep {i} @ {row['simulated_time_pt']} "
                  f"(real reconcile run {row['real_reconcile_run_id']})")
            print(f"    review checks at head: {row['review_checks_at_head']}")
            print(f"    workflow_dispatch review runs: "
                  f"{[(r['_run_id'], r['status']) for r in row['dispatch_runs']]}")
            print(f"    dispatched: {'YES ' + ' '.join(row['dispatched'][0]) if row['dispatched'] else 'no'}")
            print(f"    PR receipts posted: {[_kind(b) for b in receipts] or 'none'}")
            print(f"    card comments posted: {[_kind(b) for b in row['card_comments_posted']] or 'none'}")
            for body in receipts:
                print("      | " + body.replace("\n", "\n      | "))
            for line in row["sweep_log"]:
                print(f"    log: {line}")
            if row["write_failures"] or row["read_failures"]:
                print(f"    FAILURES: {row['write_failures']} {row['read_failures']}")
        # the criterion: from the first sweep after the second crash
        after = [r for r in rows if r["simulated_time_utc"] >= "2026-09-08T22:50:05Z"]
        holds = [b for r in after for b in r["pr_receipts_posted"] if renv.HOLD_TAG in b]
        first_holds = [b for b in after[0]["pr_receipts_posted"] if renv.HOLD_TAG in b]
        later_dispatches = [d for r in after[1:4] for d in r["dispatched"]]
        ok = (len(after) >= 4 and len(holds) == 1 and len(first_holds) == 1
              and not after[0]["dispatched"] and not later_dispatches)
        verdicts[name] = ok
        print(f"\n  CRITERION ({name[0]}): sweeps after the second crash = {len(after)}; "
              f"hold receipts on the PR = {len(holds)} (first of them: {len(first_holds)}); "
              f"dispatches on the hold sweep = {len(after[0]['dispatched'])}; "
              f"dispatches on the next three = {len(later_dispatches)} → "
              f"{'HOLDS' if ok else 'DOES NOT HOLD'}")

    # fidelity: variant A's own 15:46 receipt against what the sweep REALLY posted
    mine = result["variants"][next(iter(result["variants"]))][0]["pr_receipts_posted"]
    real_body = REAL_REDISPATCH_RECEIPT["body"]
    same = bool(mine) and mine[0] == real_body
    result["fidelity_redispatch_receipt_identical_to_real_comment"] = same
    print(f"\nFIDELITY: the replay's 15:46 PT re-dispatch receipt is byte-identical to the "
          f"real comment posted {_pt(REAL_REDISPATCH_RECEIPT['createdAt'])}: {same}")
    if not same and mine:
        print("  real:   " + real_body.replace("\n", "\n          "))
        print("  replay: " + mine[0].replace("\n", "\n          "))
    # control: the SAME driver with the evidence note taken away must do what the
    # old sweep REALLY did at 16:04 PT — post `reviewer-down` on the card.
    control = Replay(use_real_receipt=True, with_note=False).sweep(SWEEP_CLOCK[1][0])
    real_down = next(c["body"] for c in LINEAR if c["id"] == REAL_REVIEWER_DOWN_ID)
    control_same = control["card_comments_posted"] == [real_down]
    result["control_without_note"] = control
    result["control_reviewer_down_identical_to_real_comment"] = control_same
    print(f"CONTROL: without the evidence note the 16:04 PT sweep dispatched "
          f"{len(control['dispatched'])}, posted {len(control['pr_receipts_posted'])} PR receipt(s) and "
          f"{[_kind(b) for b in control['card_comments_posted']]} on the card — byte-identical to the "
          f"real reviewer-down comment of {_pt('2026-09-08T23:04:47Z')}: {control_same}")
    result["criterion"] = verdicts
    if args.json:
        Path(args.json).write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n",
                                   encoding="utf-8")
        print(f"\nfull result → {args.json}")
    return 0 if all(verdicts.values()) else 1


if __name__ == "__main__":
    sys.exit(main())
