"""RED-first tests for the daily split-ledger regeneration (DRE-3357).

The epic says the ledger is "regenerated by a scheduled job, never hand-edited,
with the generation time inside it". Until this card nothing regenerated it:
`config/split-ledger.json` was derived by hand on 2026-09-04 and aged from
there, while `scripts/ledger_context.py` calls a ledger older than
`LEDGER_MAX_AGE_HOURS` UNKNOWN and the planner reads that instead of the rates.
Freshness that depends on someone remembering is not freshness.

`.github/workflows/split-ledger.yml` is shaped on `model-drift.yml` — the one
other scheduled job here that commits a generated file to `main` — and these
tests pin the four things a later edit could quietly take away:

  1. **The cadence**, bound to the reader's own rule rather than to a number
     typed twice: daily against a 72-hour window is two missed days of margin.
  2. **The whole population.** `derive` with no `--card` discovers what it
     discovers; a `--card` list in the workflow would freeze the ledger at
     whatever someone typed the day they added it.
  3. **The staged set.** Exactly the two generated paths, PROVEN before the
     push — the model-drift guarantee, which is why that workflow is
     structurally incapable of moving a model pin.
  4. **`contents: write` and nothing else.** A scheduled job that can push to
     `main` needs no other elevated scope, and every scope it does not hold is
     a thing it cannot be edited into doing.

The staged-set tests do not read the script for the right words — they RUN it,
in a throwaway repository with a real `origin`, and check what reaches `main`.
A timestamp-only change must commit (the timestamp IS the freshness the readers
check) and a third staged path must be refused.
"""

import json
import os
import subprocess  # nosec B404 — fixed-arg git calls against a temp repo
import sys
import tempfile
import unittest
from pathlib import Path

import yaml

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

import channel_watch  # noqa: E402
import ledger_context  # noqa: E402
import split_ledger  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github" / "workflows" / "split-ledger.yml"
MEDIC_STUB = ROOT / ".github" / "workflows" / "self-medic.yml"
CONFIG_README = ROOT / "config" / "README.md"

#: The only two paths a run of this workflow may commit. Derived from the
#: module that writes them, never typed twice — a rename of either output would
#: otherwise leave the workflow staging a path nothing writes and this test
#: agreeing with it.
LEDGER_PATHS = (
    os.path.relpath(split_ledger.LEDGER_PATH, split_ledger.ROOT),
    os.path.relpath(split_ledger.DOC_PATH, split_ledger.ROOT),
)


def _doc() -> dict:
    return yaml.safe_load(WORKFLOW.read_text())


def _text() -> str:
    return WORKFLOW.read_text()


def _on(doc: dict) -> dict:
    # YAML 1.1 parses the bare key `on` as boolean True.
    on = doc.get("on", doc.get(True))
    return on if isinstance(on, dict) else {}


def _the_job(doc: dict) -> dict:
    jobs = doc.get("jobs") or {}
    assert len(jobs) == 1, "one job — the whole run is one derivation"
    return next(iter(jobs.values()))


def _steps(doc: dict) -> list:
    return [s for s in (_the_job(doc).get("steps") or []) if isinstance(s, dict)]


def _run_steps(doc: dict) -> str:
    return "\n".join(step.get("run", "") for step in _steps(doc))


def _commit_script(doc: dict) -> str:
    """The commit step's shell, the thing the executable tests below run."""
    found = [s.get("run", "") for s in _steps(doc) if "git add" in (s.get("run") or "")]
    assert len(found) == 1, f"exactly one step stages the ledger, found {len(found)}"
    return found[0]


class TheCadenceTest(unittest.TestCase):
    def setUp(self):
        self.on = _on(_doc())

    def test_it_runs_on_a_schedule_and_on_demand(self):
        schedule = self.on.get("schedule")
        self.assertTrue(schedule, "the ledger's freshness comes from a cron")
        self.assertTrue(all("cron" in entry for entry in schedule))
        self.assertIn("workflow_dispatch", self.on,
                      "a manual re-derivation must exist — it is how the first "
                      "run happens, and how a bad day is recovered")

    def test_the_schedule_is_daily(self):
        crons = [entry["cron"] for entry in self.on["schedule"]]
        self.assertTrue(
            any(channel_watch.cron_interval_hours(c) == 24.0 for c in crons),
            f"{crons} is not a daily schedule",
        )

    def test_the_cadence_leaves_margin_before_the_reader_calls_it_stale(self):
        """The producer/consumer rule in one assertion. The freshness window is
        the READER's (`ledger_context.LEDGER_MAX_AGE_HOURS`), so a daily job has
        to survive missed days — GitHub drops scheduled runs under load and
        does not retry them. Two missed days is the margin this cadence buys;
        anything slower spends it."""
        interval = min(
            h for h in (channel_watch.cron_interval_hours(e["cron"])
                        for e in self.on["schedule"]) if h
        )
        missed_days_of_margin = ledger_context.LEDGER_MAX_AGE_HOURS / interval - 1
        self.assertGreaterEqual(
            missed_days_of_margin, 2,
            f"a {interval:g}h cadence against a "
            f"{ledger_context.LEDGER_MAX_AGE_HOURS}h window leaves "
            f"{missed_days_of_margin:g} missed run(s) of margin",
        )

    def test_the_minute_is_off_the_hour(self):
        """GitHub delays scheduled jobs hardest at :00 and nothing here is
        time-critical — the same reason model-drift.yml runs at :17."""
        for entry in self.on["schedule"]:
            minute = entry["cron"].split()[0]
            self.assertNotEqual(minute, "0", f"{entry['cron']} lands on the hour")


class WhatItRunsTest(unittest.TestCase):
    def setUp(self):
        self.doc = _doc()
        self.runs = _run_steps(self.doc)

    def test_it_derives_the_ledger(self):
        self.assertIn("split_ledger.py derive", self.runs)

    def test_it_never_names_a_card(self):
        """`derive` with no `--card` discovers its own population — the seed
        cards plus whatever the successor search turns up. A card list in the
        workflow would freeze the ledger at the day it was written, and the
        discovery rules live in split_ledger.py, not here."""
        self.assertNotIn("--card", _text())

    def test_it_declares_whose_linear_budget_it_spends(self):
        """The workspace's 2,500 requests/hour are per Linear user and shared
        by every run in every repo. A run that declares nothing is reported as
        `undeclared` by scripts/check_linear_budget.py, which is the state that
        left 2026-09-05's two exhaustions unattributable."""
        self.assertIn("LINEAR_IDENTITY", _text())
        step = [s for s in _steps(self.doc) if "split_ledger.py derive" in (s.get("run") or "")]
        self.assertEqual(len(step), 1)
        env = step[0].get("env") or {}
        self.assertIn(env.get("LINEAR_IDENTITY"), ("fleet",),
                      "the scheduled run holds the fleet key, so it spends the "
                      "fleet's budget")
        self.assertIn("LINEAR_API_KEY", env)

    def test_the_timeout_names_the_budget_it_draws(self):
        job = _the_job(self.doc)
        self.assertIsInstance(job.get("timeout-minutes"), int,
                              "an unbounded scheduled job burns the Actions "
                              "budget when a live read hangs")
        self.assertIn("check_linear_budget.py", _text(),
                      "the timeout comment names where the Linear spend this "
                      "job draws is read back")


class ItCommitsOnlyWhatItGeneratesTest(unittest.TestCase):
    def setUp(self):
        self.doc = _doc()
        self.runs = _run_steps(self.doc)
        self.script = _commit_script(self.doc)

    def test_it_stages_the_two_generated_paths_by_name(self):
        for path in LEDGER_PATHS:
            self.assertIn(path, self.script)

    def test_it_never_stages_the_whole_tree(self):
        self.assertNotIn("git add .", self.runs)
        self.assertNotIn("git add -A", self.runs)
        self.assertNotIn("git add --all", self.runs)

    def test_it_proves_the_staged_set_before_pushing(self):
        """Not "we only staged two paths" — the workflow READS the index back
        and refuses anything else, so a future edit that stages a third path
        cannot smuggle it to main behind the schedule."""
        self.assertIn("git diff --cached --name-only", self.script)

    def test_it_pushes_to_main_as_the_bot(self):
        self.assertIn("agent-bureau-bot[bot]", self.script)
        self.assertIn("git push origin HEAD:main", self.script)

    def test_it_does_not_skip_a_timestamp_only_change(self):
        """The timestamp IS the freshness the readers check. A run that
        compared the ledger while ignoring `generated_at` would decide a fresh
        derivation was a no-op and leave the reader reporting UNKNOWN."""
        self.assertNotIn("generated_at", self.script)

    def test_the_checkout_and_the_push_use_the_app_token(self):
        """Not github.token: a push made with GITHUB_TOKEN triggers no
        workflows, so the ledger commit would land on main with the test suite
        never running against it."""
        steps = _steps(self.doc)
        mint = [s for s in steps if "create-github-app-token" in (s.get("uses") or "")]
        self.assertEqual(len(mint), 1, "one App token mint")
        checkout = [s for s in steps if "actions/checkout" in (s.get("uses") or "")]
        self.assertEqual(len(checkout), 1)
        token = (checkout[0].get("with") or {}).get("token") or ""
        self.assertIn(f"steps.{mint[0]['id']}.outputs.token", token)


class PermissionsTest(unittest.TestCase):
    def test_contents_write_is_the_only_elevated_permission(self):
        """It pushes a commit and does nothing else. `contents: write` is the
        whole scope; every other scope it does not hold is a thing a later edit
        cannot make it do."""
        permissions = _doc().get("permissions")
        self.assertEqual(permissions, {"contents": "write"})

    def test_no_job_widens_the_permissions(self):
        job = _the_job(_doc())
        self.assertNotIn("permissions", job,
                         "a job-level block would override the workflow's one "
                         "declared scope out of sight of the test above")


class TheVendorBoundaryIsAnsweredTest(unittest.TestCase):
    """standards/vendor-boundaries.md: this workflow touches an external
    trigger, a secrets store and a push to a protected branch, so all five
    questions are answered where the next reader of the file will find them."""

    def test_all_five_answers_are_in_the_header(self):
        header = "\n".join(
            line for line in _text().splitlines()
            if line.startswith("#") or line.startswith("  #")
        )
        self.assertIn("vendor-boundaries.md", header)
        for question in ("Q1", "Q2", "Q3", "Q4", "Q5"):
            self.assertIn(question, header, f"{question} is unanswered")


class TheMedicWatchesItTest(unittest.TestCase):
    def test_a_red_run_is_diagnosed(self):
        """DRE-2820: a workflow that can run on the default branch and that
        nothing watches is a silent failure surface. scripts/
        check_workflow_watchers.py derives the same rule; this pins the
        specific entry so a rename of the workflow's `name:` is caught here
        too."""
        name = _doc().get("name")
        watched = _on(yaml.safe_load(MEDIC_STUB.read_text()))["workflow_run"]["workflows"]
        self.assertIn(name, watched)


class TheDocumentSaysSoTest(unittest.TestCase):
    def test_the_config_readme_names_the_job_that_regenerates_the_ledger(self):
        """"Generated, not hand-edited" was true of the script and not of the
        cadence. The file that describes the ledger names what regenerates it."""
        self.assertIn("split-ledger.yml", CONFIG_README.read_text())


# --------------------------------------------------------------------------- #
# the commit step, RUN                                                         #
# --------------------------------------------------------------------------- #


def _git(*args, cwd):
    return subprocess.run(  # nosec B603 B607 — fixed args, temp repo
        ["git", *args], cwd=str(cwd), capture_output=True, text=True, check=True)


class TheCommitStepRunsTest(unittest.TestCase):
    """The staged-set guarantee, exercised rather than read for. Each test
    builds a repository with the two generated files committed and a real
    `origin`, mutates the working tree the way a run would, and runs the
    workflow's own commit script."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        root = Path(self.tmp.name)
        self.origin = root / "origin.git"
        self.work = root / "work"
        subprocess.run(  # nosec B603 B607
            ["git", "init", "--bare", "-b", "main", str(self.origin)],
            capture_output=True, check=True)
        self.work.mkdir()
        _git("init", "-b", "main", cwd=self.work)
        for path in LEDGER_PATHS:
            target = self.work / path
            target.parent.mkdir(parents=True, exist_ok=True)
        self._write_ledger("2026-09-09T04:11:00Z")
        (self.work / "agents.yaml").write_text("# a file this job may never touch\n")
        _git("add", "-A", cwd=self.work)
        self._commit("seed")
        _git("remote", "add", "origin", str(self.origin), cwd=self.work)
        _git("push", "origin", "main", cwd=self.work)
        self.before = self._origin_head()

    def _write_ledger(self, stamp: str):
        (self.work / LEDGER_PATHS[0]).write_text(
            json.dumps({"generated_at": stamp, "rows": []}, indent=2) + "\n")
        (self.work / LEDGER_PATHS[1]).write_text(f"# The split ledger\n\nGenerated **{stamp}**.\n")

    def _commit(self, message: str):
        _git("-c", "user.name=t", "-c", "user.email=t@example.com",
             "commit", "-m", message, cwd=self.work)

    def _origin_head(self) -> str:
        return _git("rev-parse", "main", cwd=self.origin).stdout.strip()

    def _run_commit_step(self):
        env = {
            "PATH": os.environ["PATH"],
            "HOME": str(self.work),
            "GIT_CONFIG_GLOBAL": os.devnull,
            "GIT_CONFIG_SYSTEM": os.devnull,
            "GH_TOKEN": "unused-in-this-harness",
        }
        return subprocess.run(  # nosec B603 B607 — the workflow's own script
            ["bash", "-e", "-c", _commit_script(_doc())],
            cwd=str(self.work), env=env, capture_output=True, text=True)

    def test_a_timestamp_only_derivation_still_commits_and_pushes(self):
        """The run the card is about: nothing changed but `generated_at`, and
        skipping it would make a fresh derivation look stale to every reader."""
        self._write_ledger("2026-09-10T04:11:00Z")
        result = self._run_commit_step()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertNotEqual(self._origin_head(), self.before,
                            "main did not move — the freshness never shipped")
        log = _git("log", "-1", "--format=%an|%ae|%s", cwd=self.origin).stdout
        self.assertIn("agent-bureau-bot[bot]", log)
        changed = _git("show", "--name-only", "--format=", "HEAD", cwd=self.origin)
        self.assertEqual(sorted(changed.stdout.split()), sorted(LEDGER_PATHS))

    def test_it_refuses_when_anything_else_is_staged(self):
        """A third path in the index — an earlier step, or a later edit to this
        workflow — is refused, and main does not move."""
        self._write_ledger("2026-09-10T04:11:00Z")
        (self.work / "agents.yaml").write_text("# a quietly rewritten ladder\n")
        _git("add", "agents.yaml", cwd=self.work)
        result = self._run_commit_step()
        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        self.assertIn("agents.yaml", result.stdout + result.stderr)
        self.assertEqual(self._origin_head(), self.before,
                         "main moved on a run that should have refused")

    def test_an_untracked_neighbour_is_not_swept_in(self):
        """The other half of the same guarantee: a file the job never staged
        stays out of the commit rather than riding along."""
        self._write_ledger("2026-09-10T04:11:00Z")
        (self.work / "stray.txt").write_text("left behind by some other step\n")
        result = self._run_commit_step()
        self.assertEqual(result.returncode, 0, result.stderr)
        changed = _git("show", "--name-only", "--format=", "HEAD", cwd=self.origin)
        self.assertNotIn("stray.txt", changed.stdout)


if __name__ == "__main__":
    unittest.main()
