"""RED-first tests for the daily split-ledger regeneration (DRE-3357).

The epic says the ledger is "regenerated by a scheduled job, never hand-edited,
with the generation time inside it". Until this card nothing regenerated it:
`config/split-ledger.json` was derived by hand on 2026-09-04 and aged from
there, while `scripts/ledger_context.py` calls a ledger older than
`LEDGER_MAX_AGE_HOURS` UNKNOWN and the planner reads that instead of the rates.
Freshness that depends on someone remembering is not freshness.

`.github/workflows/split-ledger.yml` is shaped on `model-drift.yml` — the one
other scheduled job here that commits a generated file — and these tests pin
the four things a later edit could quietly take away.

DRE-3879 changed where that commit LANDS and nothing else about this job. Both
jobs used to end in `git push origin HEAD:main`, which branch protection
refuses (`GH006`), so the ledger had failed to save itself every day since the
card was opened. It now rides one pull request off `bot/split-ledger`, and the
tests below watch `main` staying exactly where it was.

  1. **The cadence**, bound to the reader's own rule rather than to a number
     typed twice: daily against a 72-hour window is two missed days of margin.
  2. **The whole population.** `derive` with no `--card` discovers what it
     discovers; a `--card` list in the workflow would freeze the ledger at
     whatever someone typed the day they added it.
  3. **The staged set.** Exactly the two generated paths, PROVEN before the
     push — the model-drift guarantee, which is why that workflow is
     structurally incapable of moving a model pin.
  4. **`contents: write` and nothing else.** A scheduled job that can push to
     `main` needs no other elevated scope, and every scope it does not hold is
     a thing it cannot be edited into doing.

The staged-set tests do not read the script for the right words — they RUN it,
in a throwaway repository with a real `origin`, and check what reaches `main`.
A timestamp-only change must commit (the timestamp IS the freshness the readers
check) and a third staged path must be refused.
"""

import json
import os
import sys
import unittest
from pathlib import Path

import yaml

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))

import bot_branch_harness as H  # noqa: E402
import bot_branch_pr  # noqa: E402
import channel_watch  # noqa: E402
import ledger_context  # noqa: E402
import split_ledger  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github" / "workflows" / "split-ledger.yml"
MEDIC_STUB = ROOT / ".github" / "workflows" / "self-medic.yml"
CONFIG_README = ROOT / "config" / "README.md"

#: The only two paths a run of this workflow may commit. Derived from the
#: module that writes them, never typed twice — a rename of either output would
#: otherwise leave the workflow staging a path nothing writes and this test
#: agreeing with it.
LEDGER_PATHS = (
    os.path.relpath(split_ledger.LEDGER_PATH, split_ledger.ROOT),
    os.path.relpath(split_ledger.DOC_PATH, split_ledger.ROOT),
)


def _doc() -> dict:
    return yaml.safe_load(WORKFLOW.read_text())


def _text() -> str:
    return WORKFLOW.read_text()


def _uncommented(text: str) -> str:
    """`text` with its comment lines dropped — YAML's and the shell's alike.

    The tests below assert on what the workflow DOES. A file this heavily
    commented would otherwise fail them for explaining the rule it follows,
    which is the opposite of the incentive we want.
    """
    return "\n".join(line for line in text.splitlines()
                     if not line.lstrip().startswith("#"))


def _on(doc: dict) -> dict:
    # YAML 1.1 parses the bare key `on` as boolean True.
    on = doc.get("on", doc.get(True))
    return on if isinstance(on, dict) else {}


def _the_job(doc: dict) -> dict:
    jobs = doc.get("jobs") or {}
    assert len(jobs) == 1, "one job — the whole run is one derivation"
    return next(iter(jobs.values()))


def _steps(doc: dict) -> list:
    return [s for s in (_the_job(doc).get("steps") or []) if isinstance(s, dict)]


def _run_steps(doc: dict) -> str:
    return "\n".join(step.get("run", "") for step in _steps(doc))


def _commit_script(doc: dict) -> str:
    """The publishing step's shell, the thing the executable tests below run.

    Since DRE-3879 the step hands the work to `scripts/bot_branch_pr.py`
    rather than spelling out a commit and a push to `main` — that push is the
    one branch protection refuses, and it had failed every day since this
    card's ancestor was opened.
    """
    found = [s.get("run", "") for s in _steps(doc)
             if "bot_branch_pr.py" in (s.get("run") or "")]
    assert len(found) == 1, f"exactly one step publishes the ledger, found {len(found)}"
    return found[0]


class TheCadenceTest(unittest.TestCase):
    def setUp(self):
        self.on = _on(_doc())

    def test_it_runs_on_a_schedule_and_on_demand(self):
        schedule = self.on.get("schedule")
        self.assertTrue(schedule, "the ledger's freshness comes from a cron")
        self.assertTrue(all("cron" in entry for entry in schedule))
        self.assertIn("workflow_dispatch", self.on,
                      "a manual re-derivation must exist — it is how the first "
                      "run happens, and how a bad day is recovered")

    def test_the_schedule_is_daily(self):
        crons = [entry["cron"] for entry in self.on["schedule"]]
        self.assertTrue(
            any(channel_watch.cron_interval_hours(c) == 24.0 for c in crons),
            f"{crons} is not a daily schedule",
        )

    def test_the_cadence_leaves_margin_before_the_reader_calls_it_stale(self):
        """The producer/consumer rule in one assertion. The freshness window is
        the READER's (`ledger_context.LEDGER_MAX_AGE_HOURS`), so a daily job has
        to survive missed days — GitHub drops scheduled runs under load and
        does not retry them. Two missed days is the margin this cadence buys;
        anything slower spends it."""
        interval = min(
            h for h in (channel_watch.cron_interval_hours(e["cron"])
                        for e in self.on["schedule"]) if h
        )
        missed_days_of_margin = ledger_context.LEDGER_MAX_AGE_HOURS / interval - 1
        self.assertGreaterEqual(
            missed_days_of_margin, 2,
            f"a {interval:g}h cadence against a "
            f"{ledger_context.LEDGER_MAX_AGE_HOURS}h window leaves "
            f"{missed_days_of_margin:g} missed run(s) of margin",
        )

    def test_the_minute_is_off_the_hour(self):
        """GitHub delays scheduled jobs hardest at :00 and nothing here is
        time-critical — the same reason model-drift.yml runs at :17."""
        for entry in self.on["schedule"]:
            minute = entry["cron"].split()[0]
            self.assertNotEqual(minute, "0", f"{entry['cron']} lands on the hour")


class WhatItRunsTest(unittest.TestCase):
    def setUp(self):
        self.doc = _doc()
        self.runs = _run_steps(self.doc)

    def test_it_derives_the_ledger(self):
        self.assertIn("split_ledger.py derive", self.runs)

    def test_it_never_names_a_card(self):
        """`derive` with no `--card` discovers its own population — the seed
        cards plus whatever the successor search turns up. A card list in the
        workflow would freeze the ledger at the day it was written, and the
        discovery rules live in split_ledger.py, not here."""
        self.assertNotIn("--card", _uncommented(_text()))

    def test_it_declares_whose_linear_budget_it_spends(self):
        """The workspace's 2,500 requests/hour are per Linear user and shared
        by every run in every repo. A run that declares nothing is reported as
        `undeclared` by scripts/check_linear_budget.py, which is the state that
        left 2026-09-05's two exhaustions unattributable."""
        self.assertIn("LINEAR_IDENTITY", _text())
        step = [s for s in _steps(self.doc) if "split_ledger.py derive" in (s.get("run") or "")]
        self.assertEqual(len(step), 1)
        env = step[0].get("env") or {}
        self.assertIn(env.get("LINEAR_IDENTITY"), ("fleet",),
                      "the scheduled run holds the fleet key, so it spends the "
                      "fleet's budget")
        self.assertIn("LINEAR_API_KEY", env)

    def test_the_timeout_names_the_budget_it_draws(self):
        job = _the_job(self.doc)
        self.assertIsInstance(job.get("timeout-minutes"), int,
                              "an unbounded scheduled job burns the Actions "
                              "budget when a live read hangs")
        self.assertIn("check_linear_budget.py", _text(),
                      "the timeout comment names where the Linear spend this "
                      "job draws is read back")


class ItCommitsOnlyWhatItGeneratesTest(unittest.TestCase):
    def setUp(self):
        self.doc = _doc()
        self.runs = _run_steps(self.doc)
        self.script = _commit_script(self.doc)

    def test_it_stages_the_two_generated_paths_by_name(self):
        for path in LEDGER_PATHS:
            self.assertIn(path, self.script)

    def test_it_never_stages_the_whole_tree(self):
        self.assertNotIn("git add .", self.runs)
        self.assertNotIn("git add -A", self.runs)
        self.assertNotIn("git add --all", self.runs)

    def test_it_proves_the_staged_set_before_pushing(self):
        """Not "we only staged two paths" — the index is READ BACK and
        anything else refused, so a future edit that stages a third path
        cannot smuggle it behind the schedule. The proof moved into
        `bot_branch_pr.publish` with the rest of the step (DRE-3879); this
        pins that it is still made, and the publisher's own suite runs it."""
        self.assertEqual(
            bot_branch_pr.unexpected_staged(list(LEDGER_PATHS) + ["agents.yaml"],
                                            list(LEDGER_PATHS)),
            ["agents.yaml"])

    def test_it_commits_as_the_bot_and_never_pushes_to_main(self):
        """DRE-3879. `git push origin HEAD:main` is what branch protection
        refused with GH006 every morning; the ledger now rides a pull request
        off `bot/split-ledger`, and the bot identity comes from the publisher
        rather than from a second copy in this file."""
        self.assertEqual(bot_branch_pr.BOT_NAME, "agent-bureau-bot[bot]")
        self.assertIn("--branch bot/split-ledger", self.script)
        self.assertNotIn("HEAD:main", _uncommented(_text()))
        self.assertNotRegex(_uncommented(_text()), r"git\s+push[^\n]*\bmain\b")

    def test_it_does_not_skip_a_timestamp_only_change(self):
        """The timestamp IS the freshness the readers check. A run that
        compared the ledger while ignoring `generated_at` would decide a fresh
        derivation was a no-op and leave the reader reporting UNKNOWN. Comments
        are stripped first — the script is welcome to EXPLAIN the rule, it just
        may not implement an exception to it."""
        self.assertNotIn("generated_at", _uncommented(self.script))

    def test_the_checkout_and_the_push_use_the_app_token(self):
        """Not github.token: a push made with GITHUB_TOKEN triggers no
        workflows, so the ledger commit would land on main with the test suite
        never running against it."""
        steps = _steps(self.doc)
        mint = [s for s in steps if "create-github-app-token" in (s.get("uses") or "")]
        self.assertEqual(len(mint), 1, "one App token mint")
        checkout = [s for s in steps if "actions/checkout" in (s.get("uses") or "")]
        self.assertEqual(len(checkout), 1)
        token = (checkout[0].get("with") or {}).get("token") or ""
        self.assertIn(f"steps.{mint[0]['id']}.outputs.token", token)


class PermissionsTest(unittest.TestCase):
    def test_contents_write_is_the_only_elevated_permission(self):
        """It pushes a commit and does nothing else. `contents: write` is the
        whole scope; every other scope it does not hold is a thing a later edit
        cannot make it do."""
        permissions = _doc().get("permissions")
        self.assertEqual(permissions, {"contents": "write"})

    def test_no_job_widens_the_permissions(self):
        job = _the_job(_doc())
        self.assertNotIn("permissions", job,
                         "a job-level block would override the workflow's one "
                         "declared scope out of sight of the test above")


class TheVendorBoundaryIsAnsweredTest(unittest.TestCase):
    """standards/vendor-boundaries.md: this workflow touches an external
    trigger, a secrets store and a push to a protected branch, so all five
    questions are answered where the next reader of the file will find them."""

    def test_all_five_answers_are_in_the_header(self):
        header = "\n".join(
            line for line in _text().splitlines()
            if line.startswith("#") or line.startswith("  #")
        )
        self.assertIn("vendor-boundaries.md", header)
        for question in ("Q1", "Q2", "Q3", "Q4", "Q5"):
            self.assertIn(question, header, f"{question} is unanswered")


class TheMedicWatchesItTest(unittest.TestCase):
    def test_a_red_run_is_diagnosed(self):
        """DRE-2820: a workflow that can run on the default branch and that
        nothing watches is a silent failure surface. scripts/
        check_workflow_watchers.py derives the same rule; this pins the
        specific entry so a rename of the workflow's `name:` is caught here
        too."""
        name = _doc().get("name")
        watched = _on(yaml.safe_load(MEDIC_STUB.read_text()))["workflow_run"]["workflows"]
        self.assertIn(name, watched)


class TheDocumentSaysSoTest(unittest.TestCase):
    def test_the_config_readme_names_the_job_that_regenerates_the_ledger(self):
        """"Generated, not hand-edited" was true of the script and not of the
        cadence. The file that describes the ledger names what regenerates it."""
        self.assertIn("split-ledger.yml", CONFIG_README.read_text())


# --------------------------------------------------------------------------- #
# the commit step, RUN                                                         #
# --------------------------------------------------------------------------- #


class ThePublishStepRunsTest(unittest.TestCase):
    """The staged-set guarantee, exercised rather than read for. Each test
    builds a repository with the two generated files committed and a real
    `origin`, mutates the working tree the way a run would, and runs the
    workflow's own publishing script against a fake `gh`.

    Since DRE-3879 what is watched is `bot/split-ledger` — and `main`, which
    must not move.
    """

    BRANCH = "bot/split-ledger"

    def setUp(self):
        self.repo = H.BotBranchRepo(self.addCleanup)
        self._write_ledger("2026-09-09T04:11:00Z")
        self.repo.write("agents.yaml", "# a file this job may never touch\n")
        self.repo.seed()
        self.before = self.repo.origin_ref("main")

    def _write_ledger(self, stamp: str):
        self.repo.write(LEDGER_PATHS[0],
                        json.dumps({"generated_at": stamp, "rows": []},
                                   indent=2) + "\n")
        self.repo.write(LEDGER_PATHS[1],
                        f"# The split ledger\n\nGenerated **{stamp}**.\n")

    def _run_publish_step(self):
        return self.repo.run(_commit_script(_doc()))

    def test_a_timestamp_only_derivation_still_ships(self):
        """The run the card is about: nothing changed but `generated_at`, and
        skipping it would make a fresh derivation look stale to every reader."""
        self._write_ledger("2026-09-10T04:11:00Z")
        result = self._run_publish_step()
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertTrue(self.repo.origin_ref(self.BRANCH),
                        "the branch never moved — the freshness never shipped")
        self.assertIn("agent-bureau-bot[bot]", self.repo.origin_log(self.BRANCH))
        self.assertEqual(self.repo.origin_files(self.BRANCH),
                         sorted(LEDGER_PATHS))

    def test_main_is_never_touched(self):
        """The defect this card fixes, watched directly: branch protection
        refuses a push here, so the job must not attempt one."""
        self._write_ledger("2026-09-10T04:11:00Z")
        self.assertEqual(self._run_publish_step().returncode, 0)
        self.assertEqual(self.repo.origin_ref("main"), self.before)

    def test_it_refuses_when_anything_else_is_staged(self):
        """A third path in the index — an earlier step, or a later edit to this
        workflow — is refused, and nothing is pushed."""
        self._write_ledger("2026-09-10T04:11:00Z")
        self.repo.write("agents.yaml", "# a quietly rewritten ladder\n")
        H.git("add", "agents.yaml", cwd=self.repo.work)
        result = self._run_publish_step()
        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        self.assertIn("agents.yaml", result.stdout + result.stderr)
        self.assertEqual(self.repo.origin_ref(self.BRANCH), "")
        self.assertEqual(self.repo.origin_ref("main"), self.before)

    def test_an_untracked_neighbour_is_not_swept_in(self):
        """The other half of the same guarantee: a file the job never staged
        stays out of the commit rather than riding along."""
        self._write_ledger("2026-09-10T04:11:00Z")
        self.repo.write("stray.txt", "left behind by some other step\n")
        result = self._run_publish_step()
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertNotIn("stray.txt", self.repo.origin_files(self.BRANCH))


if __name__ == "__main__":
    unittest.main()
