#!/usr/bin/env python3
"""The plan artifact — the epic's CEO-facing output, as a checkable thing (DRE-2720).

An epic used to produce a plain-text Linear comment: a medium that cannot hold
a mockup, cannot be navigated, and whose KPI section is prose. Prose is the
whole problem — "did it move the number" becomes a memory exercise, which is
the failure KPI objective O10 exists to prevent
(architecture/wave-plans/README.md:54 — "predicting two and moving two is a
result; moving two and then naming them is a story"), reintroduced one level
down.

So the artifact is markdown with a fixed shape, and this module is the
mechanical form of that shape (the human form is standards/plan-artifact.md):

  check   — the seven sections are present, the KPI block parses and carries
            the fields a close-out diffs, and the visual model is a live
            mockup or a stated reason.
  kpis    — the predictions, as records.
  closeout— prediction vs outcome, including the O10 story case: an outcome
            reported for a KPI nobody predicted comes back as `unpredicted`.
  render  — plan.html, the build output. Anchored per section AND per
            paragraph, so feedback lands on the thing it is about; the KPI
            records survive into the page as JSON; a UI epic's mockup is
            passed through as live markup under the design tokens.
  publish — writes the page and its source to plans/<epic>/ under a portal
            checkout. The path is a pure function of the epic id, so revision
            two lands on top of revision one and the CEO's link never moves.
  version-record — what changed since the published previous version,
            generated by diffing it against the new one. Nobody writes it.

Pure functions over strings with one small filesystem seam (publish), so the
plan workflow, a close-out, and the tests all run the same code.

The planner gains NO capability from any of this: it writes markdown with the
`Write` tool it already has, and the run turns that into the artifact.
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
from html.parser import HTMLParser

# --- The seven sections ------------------------------------------------------
#
# Canonical keys, in the order the artifact reads. `render` and the version
# record both walk this list, so a section added here appears in both.
REQUIRED_SECTIONS: list[str] = [
    "business case",
    "kpis",
    "risk assessment",
    "outcome",
    "visual model",
    "the cards",
    "proof and demo",
]

# The generated section (not required — revision one has no previous version).
VERSION_RECORD = "version record"

# How a section is SPELLED for the reader. Sentence case for everything except
# the acronym, which naive title-casing renders "Kpis" — in the one document
# the CEO reads.
SECTION_TITLES: dict[str, str] = {"kpis": "KPIs"}


def section_title(key: str) -> str:
    return SECTION_TITLES.get(key, key[0].upper() + key[1:])


# Heading spellings a planner will reasonably write, mapped to the canonical
# key. Deliberately narrow: a heading nobody recognises must surface as a
# MISSING section, not be silently absorbed.
_HEADING_ALIASES: dict[str, str] = {
    "business case": "business case",
    "the business case": "business case",
    "kpi": "kpis",
    "kpis": "kpis",
    "risk": "risk assessment",
    "risks": "risk assessment",
    "risk assessment": "risk assessment",
    "outcome": "outcome",
    "outcomes": "outcome",
    "visual model": "visual model",
    "cards": "the cards",
    "the cards": "the cards",
    "proof and demo": "proof and demo",
    "version record": VERSION_RECORD,
}

_DIRECTIONS = ("up", "down", "flat")

# A section heading, and the separators that introduce a trailing clause:
# planners write "## KPIs — as structured data", and the section is still KPIs.
_HEADING = re.compile(r"^(#{1,6})\s+(?P<text>.+?)\s*$", re.MULTILINE)
_TRAILING_CLAUSE = re.compile(r"\s+(?:—|–|--|:)\s.*$")

# The fenced blocks the artifact is built from. `kpis` is the machine-readable
# prediction; `mockup` is live markup rendered into the page.
_FENCE = re.compile(
    r"^```(?P<lang>[A-Za-z0-9_-]*)[^\n]*\n(?P<body>.*?)^```\s*$",
    re.MULTILINE | re.DOTALL,
)

# A markdown image — the screenshot the card says is not a visual model for a
# screen that does not exist yet.
_IMAGE = re.compile(r"!\[[^\]]*\]\([^)]+\)")

# The design-token reference a mockup must be built from: a custom property
# from console/design/tokens.css, or the stylesheet itself.
_TOKEN_USE = re.compile(r"var\(\s*--|tokens\.css")

# The explicit escape hatch for a non-UI epic, mirroring the
# `deferred: <surface> — <reason>` grammar in standards/design-parity.md: a
# stated reason, never silence.
_NOT_APPLICABLE = re.compile(
    r"not applicable\s*(?:—|–|--?|:)\s*\S", re.IGNORECASE
)

# Where a published artifact lives, relative to the portal checkout root.
PAGE_NAME = "index.html"
SOURCE_NAME = "plan.md"

# --- The mockup allowlist ----------------------------------------------------
#
# The mockup fence is the ONE place this module emits markup instead of escaped
# text, so it is the one place an injection could land — and the chain is real:
# the epic body is untrusted (standards/untrusted-content.md), the planner turns
# it into the mockup, and the run publishes that to a page the CEO opens in a
# browser. The portal's own "Add document" button strips scripts for exactly
# this reason; this path must not become the way around it.
#
# A mockup only ever needs to be STYLED by real tokens — it never needs to
# execute. So markup passes through and scripting does not, by allowlist:
# anything not named here is removed, and `mockup_defects` reports what was
# removed so the planner is told rather than quietly served a different page.

# Removed WITH their contents: their text is payload, not copy.
_MOCKUP_DROP_SUBTREE = frozenset({
    "script", "style", "iframe", "object", "embed", "applet", "noscript",
    "template", "link", "meta", "base", "form", "frame", "frameset",
})

# Kept. Structure, text, tables, form-LOOKING controls (a mockup shows a
# button; it does not submit one), and the SVG subset an icon needs.
_MOCKUP_ALLOWED_TAGS = frozenset({
    "div", "span", "p", "section", "article", "aside", "header", "footer",
    "main", "nav", "figure", "figcaption", "blockquote", "hr", "br",
    "h1", "h2", "h3", "h4", "h5", "h6",
    "ul", "ol", "li", "dl", "dt", "dd",
    "table", "thead", "tbody", "tfoot", "tr", "th", "td", "caption", "col",
    "colgroup",
    "a", "img", "picture", "source",
    "strong", "b", "em", "i", "u", "s", "small", "code", "pre", "kbd", "samp",
    "abbr", "mark", "time", "sup", "sub", "label", "legend", "fieldset",
    "button", "input", "select", "option", "optgroup", "textarea", "progress",
    "meter", "details", "summary",
    "svg", "g", "path", "circle", "ellipse", "rect", "line", "polyline",
    "polygon", "text", "tspan", "defs", "use", "symbol", "title",
})

_MOCKUP_VOID_TAGS = frozenset({
    "br", "hr", "img", "input", "source", "col", "path", "circle", "ellipse",
    "rect", "line", "polyline", "polygon", "use",
})

# Attributes any allowed tag may carry. `aria-*` and `data-*` are admitted by
# prefix below; every `on*` handler is refused by the same test.
_MOCKUP_ALLOWED_ATTRS = frozenset({
    "class", "id", "style", "title", "alt", "role", "lang", "dir",
    "width", "height", "type", "placeholder", "value", "checked", "selected",
    "disabled", "readonly", "multiple", "min", "max", "step", "rows", "cols",
    "colspan", "rowspan", "scope", "span", "for", "datetime", "open",
    "href", "src", "srcset", "sizes", "loading", "decoding",
    # The SVG geometry/paint subset.
    "viewbox", "xmlns", "fill", "stroke", "stroke-width", "stroke-linecap",
    "stroke-linejoin", "fill-rule", "clip-rule", "d", "x", "y", "cx", "cy",
    "r", "rx", "ry", "x1", "y1", "x2", "y2", "points", "transform",
    "preserveaspectratio", "opacity", "text-anchor", "font-size",
})

# URL-bearing attributes, and the schemes they may carry. Relative, fragment,
# http(s) and inline images only — `javascript:` and `data:text/html` are the
# two that turn a link into code.
_MOCKUP_URL_ATTRS = frozenset({"href", "src", "srcset"})
_UNSAFE_URL = re.compile(r"^\s*(?:javascript|vbscript|livescript|mocha)\s*:",
                         re.IGNORECASE)
_UNSAFE_DATA_URL = re.compile(r"^\s*data\s*:(?!image/(?:png|jpe?g|gif|webp|svg\+xml);)",
                              re.IGNORECASE)

# Inline-style constructs that execute or fetch. `url(...)` is refused
# outright: a mockup gets its look from tokens.css, not from a remote asset,
# and permitting it would reopen the exfiltration channel by another door.
_UNSAFE_STYLE = re.compile(
    r"expression\s*\(|javascript\s*:|vbscript\s*:|@import|behavior\s*:|"
    r"-moz-binding|url\s*\(", re.IGNORECASE)


class ArtifactError(Exception):
    """A malformed artifact — reported, never raised at a caller as a trace."""


# --- Reading the artifact ----------------------------------------------------


def normalize_heading(line: str) -> str:
    """The canonical section key a heading line names, or "" if none.

    Tolerant of case, of `&`, and of the trailing clause planners attach
    ("## KPIs — as structured data"); intolerant of unknown headings, which
    must read as a MISSING section rather than be absorbed.
    """
    m = _HEADING.match(line.strip())
    text = m.group("text") if m else line
    text = _TRAILING_CLAUSE.sub("", text.strip())
    text = text.replace("&", "and").lower()
    text = re.sub(r"[^a-z0-9 ]+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return _HEADING_ALIASES.get(text, "")


def sections(md: str) -> dict[str, str]:
    """Canonical section key → body text, for every recognised heading.

    A body stops at the next heading of ANY level, so a `###` sub-heading
    inside a section stays with that section's body while the next `##`
    starts a new one.
    """
    found: dict[str, str] = {}
    marks = [(m.start(), m.end(), m.group(0), len(m.group(1))) for m in _HEADING.finditer(md)]
    for i, (start, end, line, level) in enumerate(marks):
        key = normalize_heading(line)
        if not key:
            continue
        stop = len(md)
        for nstart, _e, nline, nlevel in marks[i + 1:]:
            if nlevel <= level or normalize_heading(nline):
                stop = nstart
                break
        found[key] = md[end:stop].strip("\n")
    return found


def missing_sections(md: str) -> list[str]:
    """The required sections the artifact does not carry, in artifact order."""
    have = sections(md)
    return [s for s in REQUIRED_SECTIONS if s not in have]


def _fences(md: str, lang: str) -> list[str]:
    return [m.group("body") for m in _FENCE.finditer(md) if m.group("lang").lower() == lang]


def kpis(md: str) -> list[dict]:
    """The KPI records the artifact predicts.

    Raises ArtifactError when the block is absent or does not parse — callers
    that want a report (defects, the CLI) catch it; there is no silent [].
    """
    blocks = _fences(md, "kpis")
    if not blocks:
        raise ArtifactError(
            "the KPIs section carries no ```kpis block — a prose KPI cannot "
            "be diffed against an outcome"
        )
    try:
        data = json.loads(blocks[0])
    except json.JSONDecodeError as e:
        raise ArtifactError(f"the ```kpis block is not valid JSON: {e}") from e
    if not isinstance(data, list):
        raise ArtifactError("the ```kpis block must be a JSON list of records")
    return data


def mockup(md: str) -> str | None:
    """The live mockup markup from the visual-model section, if any."""
    visual = sections(md).get("visual model", "")
    blocks = _fences(visual, "mockup")
    return blocks[0] if blocks else None


class _MockupSanitizer(HTMLParser):
    """Re-emit a mockup through the allowlist above, recording every removal.

    Allowlist, not blocklist: an unknown tag loses its markup (its text is
    kept, escaped) and a listed-as-dangerous tag loses its contents too. Both
    are recorded, because a sanitizer that works in silence would leave the
    planner sure the CEO is looking at what it wrote.
    """

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.out: list[str] = []
        self.removed: list[str] = []
        self._drop_depth = 0          # inside a drop-with-contents subtree
        self._emitted: list[str] = []  # tags whose end tag we must close

    # -- helpers ---------------------------------------------------------
    def _note(self, what: str) -> None:
        if what not in self.removed:
            self.removed.append(what)

    def _safe_attrs(self, tag: str, attrs) -> str:
        kept = []
        for name, value in attrs:
            name = (name or "").lower()
            value = value if value is not None else ""
            if name.startswith("on"):
                self._note(f"event handler `{name}`")
                continue
            if not (name in _MOCKUP_ALLOWED_ATTRS
                    or name.startswith(("aria-", "data-"))):
                self._note(f"attribute `{name}` on <{tag}>")
                continue
            if name in _MOCKUP_URL_ATTRS and (
                    _UNSAFE_URL.match(value) or _UNSAFE_DATA_URL.match(value)):
                self._note(f"unsafe URL in `{name}`")
                continue
            if name == "style" and _UNSAFE_STYLE.search(value):
                self._note("executable construct in a `style` attribute")
                continue
            kept.append(f' {name}="{html.escape(value, quote=True)}"')
        return "".join(kept)

    # -- HTMLParser hooks ------------------------------------------------
    def handle_starttag(self, tag, attrs):
        if self._drop_depth:
            if tag in _MOCKUP_DROP_SUBTREE:
                self._drop_depth += 1
            return
        if tag in _MOCKUP_DROP_SUBTREE:
            self._note(f"<{tag}> and its contents")
            self._drop_depth = 1
            return
        if tag not in _MOCKUP_ALLOWED_TAGS:
            self._note(f"<{tag}>")
            return
        self.out.append(f"<{tag}{self._safe_attrs(tag, attrs)}>")
        if tag not in _MOCKUP_VOID_TAGS:
            self._emitted.append(tag)

    def handle_startendtag(self, tag, attrs):
        if self._drop_depth:
            return
        if tag in _MOCKUP_DROP_SUBTREE:
            self._note(f"<{tag}> and its contents")
            return
        if tag not in _MOCKUP_ALLOWED_TAGS:
            self._note(f"<{tag}>")
            return
        self.out.append(f"<{tag}{self._safe_attrs(tag, attrs)}>")

    def handle_endtag(self, tag):
        if self._drop_depth:
            if tag in _MOCKUP_DROP_SUBTREE:
                self._drop_depth -= 1
            return
        if tag in self._emitted:
            # Close back to it, so a mis-nested input cannot leave the page
            # with an element the sanitizer never opened.
            while self._emitted:
                open_tag = self._emitted.pop()
                self.out.append(f"</{open_tag}>")
                if open_tag == tag:
                    break

    def handle_data(self, data):
        if self._drop_depth:
            return
        self.out.append(html.escape(data, quote=False))

    def handle_comment(self, data):
        return  # a comment is never load-bearing in a mockup

    def handle_decl(self, decl):
        self._note(f"<!{decl.split()[0] if decl else 'doctype'}>")

    def handle_pi(self, data):
        self._note("processing instruction")

    def result(self) -> str:
        self.close()
        tail = "".join(f"</{t}>" for t in reversed(self._emitted))
        self._emitted.clear()
        return "".join(self.out) + tail


def sanitize_mockup(markup: str) -> tuple[str, list[str]]:
    """`(safe markup, what was removed)` for a mockup block.

    The mockup renders live so the CEO sees the real screen under the real
    tokens — but "live" means styled, never executing. Everything outside the
    allowlist comes out, and the second element is what the check reports.
    """
    parser = _MockupSanitizer()
    parser.feed(markup or "")
    return parser.result(), parser.removed


# --- The check ---------------------------------------------------------------


def kpi_defects(md: str) -> list[str]:
    """Everything wrong with the KPI section, named field by field."""
    try:
        records = kpis(md)
    except ArtifactError as e:
        return [str(e)]
    if not records:
        return ["the ```kpis block is empty — an epic that predicts no number "
                "cannot be closed out against one"]
    out: list[str] = []
    for i, k in enumerate(records, 1):
        where = f"KPI {i}"
        if not isinstance(k, dict):
            out.append(f"{where}: not a record")
            continue
        name = k.get("name")
        if isinstance(name, str) and name.strip():
            where = f"KPI {name!r}"
        else:
            out.append(f"{where}: no `name`")
        if "baseline" not in k:
            out.append(f"{where}: no `baseline` — a direction with no baseline "
                       f"is 'down from what?'")
        elif isinstance(k["baseline"], bool) or not isinstance(k["baseline"], (int, float)):
            out.append(f"{where}: `baseline` must be a number, got "
                       f"{k['baseline']!r}")
        if k.get("direction") not in _DIRECTIONS:
            out.append(f"{where}: `direction` must be one of "
                       f"{', '.join(_DIRECTIONS)}, got {k.get('direction')!r}")
    return out


def visual_model_defects(md: str, ui: bool = False) -> list[str]:
    """Everything wrong with the visual model.

    A UI epic must carry a live mockup. Any epic whose visual model is only a
    screenshot fails on its own evidence: for a NEW screen there is no PNG, so
    a picture there means the CEO is approving a screen he cannot see.
    """
    visual = sections(md).get("visual model")
    if visual is None:
        return []  # missing_sections already reports the absent heading
    block = mockup(md)
    if block is not None:
        out = []
        if not _TOKEN_USE.search(block):
            out.append("the mockup uses no design token (`var(--…)` from "
                       "console/design/tokens.css) — that is a picture of a "
                       "UI, not the UI")
        # Never a silent strip: a sanitizer that works in silence would leave
        # the planner sure the CEO is looking at what it wrote.
        _safe, removed = sanitize_mockup(block)
        if removed:
            out.append(
                "the mockup contains markup the published page will not carry "
                "— a mockup is styled by tokens, it never executes. Removed: "
                + "; ".join(removed))
        return out
    if ui:
        return ["this epic's cards carry design refs, so its visual model "
                "must be a live ```mockup block built from "
                "console/design/tokens.css"]
    if _IMAGE.search(visual):
        return ["the visual model is a screenshot — for a new screen there is "
                "no PNG to point at, so it must be a live ```mockup block "
                "built from console/design/tokens.css"]
    if not visual.strip():
        return ["the visual model is empty — either a ```mockup block or "
                "'Not applicable — <reason>'"]
    if not _NOT_APPLICABLE.search(visual):
        return ["the visual model is neither a ```mockup block nor "
                "'Not applicable — <reason>'"]
    return []


def defects(md: str, ui: bool = False) -> list[str]:
    """Every reason this artifact is not fit to take the CEO's time."""
    out = [f"missing section: {s}" for s in missing_sections(md)]
    if "kpis" in sections(md):
        out += kpi_defects(md)
    out += visual_model_defects(md, ui=ui)
    return out


def is_ui_epic(child_bodies: str) -> bool:
    """Does this epic build UI? Read off the CARDS, not off the plan's say-so.

    A card carrying a `**Design:**` ref is evidence (standards/design.md); a
    prose mention of a screen is not — the same distinction
    scripts/design_parity.py already draws, and the same parser.
    """
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import design_parity

    return bool(design_parity.design_refs(child_bodies or ""))


# --- Close-out: prediction vs outcome ---------------------------------------


def closeout(md: str, outcomes: list[dict]) -> dict:
    """Diff what the plan predicted against what actually happened.

    `outcomes` is a list of `{"name": ..., "observed": <number>}`. The return
    separates three cases the CEO reads differently:
      kpis        — predicted and measured, with moved / as_predicted / target_met
      unmeasured  — predicted and never measured (the plan owes an answer)
      unpredicted — measured but never predicted: O10's story case, named
                    mechanically rather than argued about afterwards.
    """
    observed = {
        o.get("name"): o.get("observed")
        for o in outcomes
        if isinstance(o, dict) and o.get("name")
    }
    rows: list[dict] = []
    unmeasured: list[str] = []
    for k in kpis(md):
        name = k.get("name")
        if name not in observed:
            unmeasured.append(name)
            continue
        baseline, value, direction = k.get("baseline"), observed[name], k.get("direction")
        moved = value != baseline
        if direction == "up":
            as_predicted = value > baseline
        elif direction == "down":
            as_predicted = value < baseline
        else:
            as_predicted = not moved
        target = k.get("target")
        if target is None:
            target_met = None
        elif direction == "up":
            target_met = value >= target
        elif direction == "down":
            target_met = value <= target
        else:
            target_met = value == target
        rows.append({
            "name": name,
            "baseline": baseline,
            "direction": direction,
            "target": target,
            "observed": value,
            "moved": moved,
            "as_predicted": as_predicted,
            "target_met": target_met,
        })
    predicted = {k.get("name") for k in kpis(md)}
    unpredicted = [n for n in observed if n not in predicted]
    return {"kpis": rows, "unmeasured": unmeasured, "unpredicted": unpredicted}


# --- The version record ------------------------------------------------------


def _kpi_index(md: str) -> dict[str, dict]:
    try:
        return {k.get("name"): k for k in kpis(md) if isinstance(k, dict)}
    except ArtifactError:
        return {}


def _kpi_changes(previous: str, current: str) -> list[str]:
    was, now = _kpi_index(previous), _kpi_index(current)
    notes: list[str] = []
    for name in now:
        if name not in was:
            notes.append(f'added "{name}"')
    for name in was:
        if name not in now:
            notes.append(f'removed "{name}"')
    for name in now:
        if name not in was:
            continue
        for field in ("baseline", "target", "direction"):
            old, new = was[name].get(field), now[name].get(field)
            if old != new:
                notes.append(f'{field} changed for "{name}" ({old} → {new})')
    return notes


def version_record(previous: str, current: str) -> str:
    """What changed since the CEO last read this — generated, not written.

    A plan arriving in Green Light gets substantial feedback and goes round
    again; that is the normal path. The record says which sections to re-read
    AND which not to, because "where do I look" is the actual question.
    """
    was, now = sections(previous), sections(current)
    changed: list[str] = []
    unchanged: list[str] = []
    for key in REQUIRED_SECTIONS:
        title = section_title(key)
        old_body, new_body = was.get(key), now.get(key)
        if old_body is None and new_body is not None:
            changed.append(f"- **{title}** — added")
        elif old_body is not None and new_body is None:
            changed.append(f"- **{title}** — removed")
        elif (old_body or "").strip() == (new_body or "").strip():
            unchanged.append(title)
        elif key == "kpis":
            notes = _kpi_changes(previous, current)
            detail = "; ".join(notes) if notes else "revised"
            changed.append(f"- **{title}** — {detail}")
        else:
            changed.append(f"- **{title}** — revised")

    lines = ["What changed since you last read this — generated from the "
             "published version, not written by hand.", ""]
    if not changed:
        lines.append("No changes to the seven sections.")
    else:
        lines += changed
    if unchanged and changed:
        lines += ["", f"Unchanged: {', '.join(unchanged)}."]
    return "\n".join(lines)


def with_version_record(md: str, record: str) -> str:
    """Fold a generated record into the artifact, replacing any earlier one.

    Replacing, never stacking: revision three's record answers "since you last
    read it", so revision two's is history, not context.
    """
    if not record.strip():
        return md
    body = f"## Version record\n\n{record.strip()}\n"
    marks = [
        (m.start(), m.end(), m.group(0), len(m.group(1)))
        for m in _HEADING.finditer(md)
    ]
    for i, (start, _end, line, level) in enumerate(marks):
        if normalize_heading(line) != VERSION_RECORD:
            continue
        stop = len(md)
        for nstart, _e, _nl, nlevel in marks[i + 1:]:
            if nlevel <= level:
                stop = nstart
                break
        return md[:start] + body + "\n" + md[stop:].lstrip("\n")
    return md.rstrip("\n") + "\n\n" + body


# --- Publishing --------------------------------------------------------------


def epic_slug(epic: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (epic or "").strip().lower()).strip("-")


def stable_dir(epic: str) -> str:
    """The artifact's directory under the portal, from the epic id alone."""
    return f"plans/{epic_slug(epic)}"


def stable_path(epic: str) -> str:
    """The published page's path — a pure function of the epic id, which is
    what makes the CEO's link survive every revision."""
    return f"{stable_dir(epic)}/{PAGE_NAME}"


def stable_url(epic: str, base: str | None) -> str | None:
    """The public URL, or None when no portal is configured.

    None, never a guess: console-honesty rule 2 — a URL the CEO follows to a
    404 is worse than saying the artifact is attached to the run.
    """
    if not base:
        return None
    return f"{base.rstrip('/')}/{stable_dir(epic)}/"


def published_source(portal_root: str, epic: str) -> str | None:
    """The markdown of the version currently published, or None.

    This is what makes the version record generated rather than remembered:
    publish stores the source beside the page, so the next run has the text
    the CEO actually read.
    """
    path = os.path.join(portal_root, stable_dir(epic), SOURCE_NAME)
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as f:
        return f.read()


def publish(md: str, epic: str, portal_root: str, tokens_href: str | None = None) -> str:
    """Write the page and its source into the portal checkout; return the page
    path. Overwrites in place — republishing is idempotent at one location."""
    target = os.path.join(portal_root, stable_dir(epic))
    os.makedirs(target, exist_ok=True)
    page = os.path.join(target, PAGE_NAME)
    with open(page, "w", encoding="utf-8") as f:
        f.write(render(md, epic, tokens_href=tokens_href))
    with open(os.path.join(target, SOURCE_NAME), "w", encoding="utf-8") as f:
        f.write(md)
    return page


# --- Rendering ---------------------------------------------------------------

DEFAULT_TOKENS_HREF = "console/design/tokens.css"

_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Defence in depth behind the mockup allowlist: even a hole in it cannot
     execute, load a frame, or reach a third-party host. The kpi-data block
     below is a JSON DATA island, not a script — browsers never execute it,
     and script-src does not remove it from the DOM. -->
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'none'; object-src 'none'; frame-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; base-uri 'none'; form-action 'none'">
<title>{title}</title>
<link rel="stylesheet" href="{tokens}">
<style>
  body {{ margin: 0 auto; max-width: 56rem; padding: 2rem 1.5rem 6rem;
         font-family: var(--font-body, system-ui, sans-serif);
         background: var(--surface, #fff); color: var(--text, #111); }}
  section {{ scroll-margin-top: 2rem; }}
  [data-anchor] {{ position: relative; }}
  [data-anchor] > a.anchor {{ position: absolute; left: -1.25rem; opacity: 0;
         text-decoration: none; }}
  [data-anchor]:hover > a.anchor {{ opacity: .5; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ border: 1px solid var(--border, #ddd); padding: .4rem .6rem;
         text-align: left; }}
  .mockup {{ border: 1px solid var(--border, #ddd); border-radius: .5rem;
         padding: 1rem; }}
</style>
</head>
<body>
<h1 id="title">{title}</h1>
{body}
<script type="application/json" id="kpi-data">{kpis}</script>
</body>
</html>
"""


def _esc(text: str) -> str:
    return html.escape(text, quote=False)


def _inline(text: str) -> str:
    """Escape, then re-admit the two inline marks a plan actually uses."""
    out = _esc(text)
    out = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"`(.+?)`", r"<code>\1</code>", out)
    return out


def _table(rows: list[str]) -> str:
    cells = [[c.strip() for c in r.strip().strip("|").split("|")] for r in rows]
    body = [c for c in cells if not all(set(x) <= set("-: ") and x for x in c)]
    if not body:
        return ""
    head, rest = body[0], body[1:]
    out = ["<table>", "<thead><tr>"
           + "".join(f"<th>{_inline(c)}</th>" for c in head)
           + "</tr></thead>", "<tbody>"]
    for row in rest:
        out.append("<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in row) + "</tr>")
    out += ["</tbody>", "</table>"]
    return "\n".join(out)


def _render_section(key: str, body: str) -> str:
    """One section: an anchored <section>, and an anchored id per paragraph.

    Paragraph ids are numbered WITHIN the section, so editing the business
    case does not renumber the anchors a comment on the outcome is bound to.
    """
    anchor = key.replace(" ", "-")
    title = section_title(key)
    out = [f'<section id="{anchor}" data-anchor>',
           f'<a class="anchor" href="#{anchor}">#</a>',
           f"<h2>{_esc(title)}</h2>"]
    para = 0
    i = 0
    lines = body.split("\n")
    while i < len(lines):
        line = lines[i]
        if line.startswith("```"):
            lang = line[3:].strip().lower()
            block: list[str] = []
            i += 1
            while i < len(lines) and not lines[i].startswith("```"):
                block.append(lines[i])
                i += 1
            i += 1
            raw = "\n".join(block)
            if lang == "mockup":
                # Markup, not escaped text: this IS the UI, and a picture of
                # it would be the thing this card exists to replace. Through
                # the allowlist first — "live" means styled by real tokens,
                # never executing (see _MOCKUP_ALLOWED_TAGS).
                safe, _removed = sanitize_mockup(raw)
                out.append(f'<div class="mockup" id="{anchor}-mockup" '
                           f'data-anchor>'
                           f'<a class="anchor" href="#{anchor}-mockup">#</a>'
                           f"\n{safe}\n</div>")
            elif lang == "kpis":
                out.append(_kpi_table(raw, anchor))
            else:
                out.append(f"<pre><code>{_esc(raw)}</code></pre>")
            continue
        if line.strip().startswith("|"):
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                rows.append(lines[i])
                i += 1
            out.append(_table(rows))
            continue
        if re.match(r"^\s*[-*]\s+", line):
            items = []
            while i < len(lines) and re.match(r"^\s*[-*]\s+", lines[i]):
                items.append(re.sub(r"^\s*[-*]\s+", "", lines[i]))
                i += 1
            out.append("<ul>" + "".join(f"<li>{_inline(x)}</li>" for x in items)
                       + "</ul>")
            continue
        if line.startswith("#"):
            out.append(f"<h3>{_inline(line.lstrip('#').strip())}</h3>")
            i += 1
            continue
        if not line.strip():
            i += 1
            continue
        chunk = []
        while i < len(lines) and lines[i].strip() and not lines[i].startswith(
                ("```", "#")) and not lines[i].strip().startswith("|") \
                and not re.match(r"^\s*[-*]\s+", lines[i]):
            chunk.append(lines[i].strip())
            i += 1
        para += 1
        pid = f"{anchor}-p{para}"
        out.append(f'<p id="{pid}" data-anchor>'
                   f'<a class="anchor" href="#{pid}">#</a>'
                   f"{_inline(' '.join(chunk))}</p>")
    out.append("</section>")
    return "\n".join(out)


def _kpi_table(raw: str, anchor: str) -> str:
    try:
        records = json.loads(raw)
    except json.JSONDecodeError:
        return f"<pre><code>{_esc(raw)}</code></pre>"
    cols = ["name", "baseline", "unit", "direction", "target"]
    out = [f'<table id="{anchor}-table"><thead><tr>'
           + "".join(f"<th>{c}</th>" for c in cols) + "</tr></thead><tbody>"]
    for k in records:
        if not isinstance(k, dict):
            continue
        out.append("<tr>" + "".join(
            f"<td>{_esc(str(k.get(c, '')))}</td>" for c in cols) + "</tr>")
    out.append("</tbody></table>")
    return "\n".join(out)


def render(md: str, epic: str, tokens_href: str | None = None) -> str:
    """plan.html — the build output. The planner writes markdown; the run
    produces this, so the artifact is an output rather than a capability."""
    found = sections(md)
    title_m = re.search(r"^#\s+(?P<t>.+)$", md, re.MULTILINE)
    title = title_m.group("t").strip() if title_m else epic
    order = [VERSION_RECORD] + REQUIRED_SECTIONS
    body = "\n".join(_render_section(k, found[k]) for k in order if k in found)
    try:
        payload = json.dumps(kpis(md))
    except ArtifactError:
        payload = "[]"
    return _PAGE.format(
        title=_esc(f"{epic} — {title}" if epic and epic not in title else title),
        tokens=_esc(tokens_href or DEFAULT_TOKENS_HREF),
        body=body,
        kpis=payload.replace("</", "<\\/"),
    )


# --- CLI ---------------------------------------------------------------------


def _read(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except OSError as e:
        raise ArtifactError(f"cannot read artifact {path}: {e.strerror}") from e


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    c = sub.add_parser("check", help="every reason this artifact is not fit")
    c.add_argument("artifact")
    c.add_argument("--ui", action="store_true",
                   help="this epic builds UI: a live mockup is mandatory")

    k = sub.add_parser("kpis", help="the predictions, as JSON")
    k.add_argument("artifact")

    r = sub.add_parser("render", help="write plan.html")
    r.add_argument("artifact")
    r.add_argument("--epic", required=True)
    r.add_argument("-o", "--out", required=True)
    r.add_argument("--tokens", default=None)

    u = sub.add_parser("url", help="the stable URL, or nothing")
    u.add_argument("epic")
    u.add_argument("--base", default=os.environ.get("PLAN_PORTAL_BASE_URL", ""))

    pa = sub.add_parser("path", help="the stable path under the portal")
    pa.add_argument("epic")

    p = sub.add_parser("publish", help="write the page + source into a portal")
    p.add_argument("artifact")
    p.add_argument("--epic", required=True)
    p.add_argument("--portal", required=True)
    p.add_argument("--base", default=os.environ.get("PLAN_PORTAL_BASE_URL", ""))
    p.add_argument("--tokens", default=None)

    v = sub.add_parser("version-record",
                       help="what changed since the published version")
    v.add_argument("artifact")
    v.add_argument("--epic", required=True)
    v.add_argument("--portal", required=True)

    w = sub.add_parser("with-version-record",
                       help="fold a generated record into the artifact")
    w.add_argument("artifact")
    w.add_argument("record")
    w.add_argument("-o", "--out", required=True)

    sub.add_parser("ui-epic",
                   help="read child card bodies on stdin; true if UI work")

    co = sub.add_parser("closeout", help="prediction vs outcome, as JSON")
    co.add_argument("artifact")
    co.add_argument("outcomes")

    args = ap.parse_args(argv)

    if args.cmd == "ui-epic":
        print("true" if is_ui_epic(sys.stdin.read()) else "false")
        return 0
    if args.cmd == "path":
        print(stable_path(args.epic))
        return 0
    if args.cmd == "url":
        url = stable_url(args.epic, args.base)
        if url:
            print(url)
        return 0

    if args.cmd == "check":
        found = defects(_read(args.artifact), ui=args.ui)
        if not found:
            print("plan artifact: complete")
            return 0
        print(f"plan artifact: {len(found)} defect(s)", file=sys.stderr)
        for d in found:
            print(f"  - {d}", file=sys.stderr)
        return 1

    if args.cmd == "kpis":
        print(json.dumps(kpis(_read(args.artifact)), indent=2))
        return 0

    if args.cmd == "render":
        out = render(_read(args.artifact), args.epic, tokens_href=args.tokens)
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(out)
        print(args.out)
        return 0

    if args.cmd == "publish":
        page = publish(_read(args.artifact), args.epic, args.portal,
                       tokens_href=args.tokens)
        url = stable_url(args.epic, args.base)
        print(url or page)
        return 0

    if args.cmd == "version-record":
        previous = published_source(args.portal, args.epic)
        if previous is None:
            return 0  # revision one: nothing to diff, and none invented
        sys.stdout.write(version_record(previous, _read(args.artifact)))
        return 0

    if args.cmd == "with-version-record":
        merged = with_version_record(_read(args.artifact), _read(args.record))
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(merged)
        print(args.out)
        return 0

    if args.cmd == "closeout":
        outcomes = json.loads(_read(args.outcomes))
        print(json.dumps(closeout(_read(args.artifact), outcomes), indent=2))
        return 0

    return 2


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except ArtifactError as e:
        # The only abort: explicit, at top level, CLI-only — a malformed
        # artifact is a finding for the planner, never a traceback.
        raise SystemExit(f"plan artifact: {e}")
